-- ==============================================================================
-- ShareToDo - Complete Database Schema with Authentication & RLS & Sharing
--
-- WHERE TO RUN
--   Supabase Dashboard -> SQL Editor.
--
-- THIS FILE IS IDEMPOTENT AND IS ALSO THE MIGRATION
--   Every statement is guarded (IF NOT EXISTS / OR REPLACE / DROP ... IF EXISTS),
--   so re-running the whole file on an existing database is safe: it creates what
--   is missing, refreshes every policy and function, and never drops your rows.
--   Applying an update == re-running this file.
--
-- WHAT IS IN HERE
--   1. tables ........ todos (activities), notes, todo_shares, profiles
--   2. approval ...... a signed-up user is "pending" until an admin approves them;
--                      while pending, RLS returns no rows for them
--   3. sharing ....... group-scoped: one share row = one (person, group) grant,
--                      and it governs both todos and notes of that group
--      group_name IS NULL        -> the whole list is shared
--      group_name IS NOT NULL    -> only that subgroup is shared
--   4. admin ......... SECURITY DEFINER functions an admin calls from the app to
--                      list/approve/delete users and reset their passwords
--
-- GRANTING YOURSELF ADMIN (run separately, after this file)
--   update public.profiles set is_admin = true, approved = true
--   where lower(email) = lower('you@example.com');
--   (there is deliberately no API that can grant admin rights)
-- ==============================================================================

create extension if not exists pgcrypto with schema extensions;


-- ==============================================================================
-- 1. TABLES
-- ==============================================================================

-- ---------------------------------------------------------------- 1.1 todos
CREATE TABLE IF NOT EXISTS public.todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  group_name TEXT DEFAULT 'Generale',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid()
);

-- Assicurati che le colonne esistano se la tabella era già creata
ALTER TABLE public.todos ADD COLUMN IF NOT EXISTS group_name TEXT DEFAULT 'Generale';
ALTER TABLE public.todos ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_todos_user_id ON public.todos(user_id);
CREATE INDEX IF NOT EXISTS idx_todos_group_name ON public.todos(group_name);


-- ---------------------------------------------------------------- 1.2 notes
-- Free-form notes. Same shape as a todo (`group_name` + `user_id`) on purpose:
-- they then ride on exactly the same sharing rules and the same UI patterns.
CREATE TABLE IF NOT EXISTS public.notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  group_name TEXT DEFAULT 'Generale',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid()
);

ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS body TEXT NOT NULL DEFAULT '';
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS group_name TEXT DEFAULT 'Generale';
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();

CREATE INDEX IF NOT EXISTS idx_notes_user_id ON public.notes(user_id);
CREATE INDEX IF NOT EXISTS idx_notes_group_name ON public.notes(group_name);

-- updated_at is maintained by the database so every writer agrees on it.
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS on_notes_updated ON public.notes;
CREATE TRIGGER on_notes_updated
  BEFORE UPDATE ON public.notes
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();


-- ---------------------------------------------------------- 1.3 todo_shares
-- Grants of access to another person. Despite the name it is NOT tied to the
-- `todos` table: it authorises a (owner, group) pair and is what both the todos
-- and the notes policies consult. A rename would have broken every deploy, so the
-- historical name stays.
CREATE TABLE IF NOT EXISTS public.todo_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL DEFAULT auth.uid(),
  shared_with_email TEXT NOT NULL,
  shared_with_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  group_name TEXT,
  permission TEXT CHECK (permission IN ('read', 'edit')) DEFAULT 'edit',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.todo_shares ADD COLUMN IF NOT EXISTS group_name TEXT;

-- L'unicità comprende il gruppo: la stessa persona può ricevere più gruppi.
-- COALESCE perché in un indice UNIQUE i NULL sono tutti distinti fra loro, quindi
-- senza di esso si potrebbero creare più condivisioni "intera lista" per la stessa email.
ALTER TABLE public.todo_shares DROP CONSTRAINT IF EXISTS todo_shares_owner_id_shared_with_email_key;
DROP INDEX IF EXISTS public.idx_todo_shares_unique;
CREATE UNIQUE INDEX IF NOT EXISTS idx_todo_shares_unique
  ON public.todo_shares (owner_id, LOWER(shared_with_email), COALESCE(group_name, '__all__'));

CREATE INDEX IF NOT EXISTS idx_todo_shares_owner ON public.todo_shares(owner_id);
CREATE INDEX IF NOT EXISTS idx_todo_shares_email ON public.todo_shares(LOWER(shared_with_email));
CREATE INDEX IF NOT EXISTS idx_todo_shares_recipient ON public.todo_shares(shared_with_id);


-- ------------------------------------------------------------- 1.4 profiles
-- One row per auth user, holding the two flags the app cannot keep client-side.
-- Deliberately NOT writable by its owner: a user must not be able to approve or
-- promote themselves. Only the admin RPCs (section 4) touch `approved`/`is_admin`.
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  approved BOOLEAN NOT NULL DEFAULT FALSE,
  is_admin BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS approved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES auth.users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(LOWER(email));
CREATE INDEX IF NOT EXISTS idx_profiles_pending ON public.profiles(approved) WHERE approved = FALSE;


-- ==============================================================================
-- 2. PROFILES BOOKKEEPING
-- ==============================================================================

-- When a new user registers, link the shares that were already sent to their
-- email (invitations made before the invitee had an account).
CREATE OR REPLACE FUNCTION public.handle_new_user_shares()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.todo_shares
  SET shared_with_id = NEW.id
  WHERE LOWER(shared_with_email) = LOWER(NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created_shares ON auth.users;
CREATE TRIGGER on_auth_user_created_shares
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_shares();

-- A new signup starts UN-APPROVED and waiting for an admin.
CREATE OR REPLACE FUNCTION public.handle_new_user_profile()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (NEW.id, LOWER(NEW.email))
  ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_profile ON auth.users;
CREATE TRIGGER on_auth_user_created_profile
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_profile();

-- Keep the denormalised email in step when the address changes.
CREATE OR REPLACE FUNCTION public.handle_user_email_change()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  UPDATE public.profiles SET email = LOWER(NEW.email) WHERE id = NEW.id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_email_changed ON auth.users;
CREATE TRIGGER on_auth_user_email_changed
  AFTER UPDATE OF email ON auth.users
  FOR EACH ROW
  WHEN (OLD.email IS DISTINCT FROM NEW.email)
  EXECUTE FUNCTION public.handle_user_email_change();

-- Grandfather every account that predates this schema as approved, exactly once.
-- ON CONFLICT DO NOTHING is what makes re-running this file harmless: an
-- account the admin deliberately left (or put back) as pending is never re-approved.
INSERT INTO public.profiles (id, email, approved, approved_at)
SELECT u.id, LOWER(u.email), TRUE, NOW()
FROM auth.users u
ON CONFLICT (id) DO NOTHING;

-- Backfill emails for any profile row created before the column existed.
UPDATE public.profiles p
SET email = LOWER(u.email)
FROM auth.users u
WHERE u.id = p.id AND (p.email IS NULL OR p.email IS DISTINCT FROM LOWER(u.email));


-- ==============================================================================
-- 3. HELPERS USED BY THE POLICIES
-- SECURITY DEFINER: they read `profiles`, which the caller may not be allowed to
-- read (or, for an unapproved user, may not be allowed to read at all). Without
-- DEFINER the policy would recurse into the very table it is guarding.
-- STABLE so Postgres can cache the result within a statement instead of running
-- a subquery per row for the whole list.
-- ==============================================================================

CREATE OR REPLACE FUNCTION public.is_admin(uid UUID)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE((SELECT p.is_admin FROM public.profiles p WHERE p.id = uid), FALSE);
$$;

CREATE OR REPLACE FUNCTION public.is_approved(uid UUID)
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE((SELECT p.approved FROM public.profiles p WHERE p.id = uid), FALSE);
$$;


-- ==============================================================================
-- 4. ADMIN FUNCTIONS (called from the app with supabase.rpc(...))
--
-- Every one of them starts by re-checking public.is_admin(auth.uid()) — the
-- client-side route guard is a convenience, not the security boundary. They are
-- SECURITY DEFINER so they can reach auth.users; EXECUTE is revoked from anon and
-- public, and granted only to authenticated.
-- ==============================================================================

-- --------------------------------------------------------- 4.1 list users
DROP FUNCTION IF EXISTS public.admin_list_users();
CREATE OR REPLACE FUNCTION public.admin_list_users()
RETURNS TABLE (
  id UUID,
  email TEXT,
  approved BOOLEAN,
  is_admin BOOLEAN,
  created_at TIMESTAMPTZ,
  last_sign_in_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  todo_count BIGINT,
  note_count BIGINT,
  share_count BIGINT
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'admin_list_users: not authorized' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    u.id,
    u.email::TEXT,
    COALESCE(p.approved, FALSE),
    COALESCE(p.is_admin, FALSE),
    u.created_at,
    u.last_sign_in_at,
    p.approved_at,
    (SELECT COUNT(*) FROM public.todos t WHERE t.user_id = u.id),
    (SELECT COUNT(*) FROM public.notes n WHERE n.user_id = u.id),
    (SELECT COUNT(*) FROM public.todo_shares s
      WHERE s.owner_id = u.id OR s.shared_with_id = u.id)
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.id = u.id
  ORDER BY COALESCE(p.approved, FALSE) ASC, u.created_at DESC;
END;
$$;

-- ------------------------------------------------------ 4.2 set password
-- Sets the password directly (the admin then hands it over out-of-band). GoTrue
-- verifies bcrypt, and pgcrypto's `crypt`/`gen_salt('bf')` produce exactly that,
-- so a password written here logs in normally.
DROP FUNCTION IF EXISTS public.admin_set_password(UUID, TEXT);
CREATE OR REPLACE FUNCTION public.admin_set_password(p_user_id UUID, p_password TEXT)
RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions AS $$
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'admin_set_password: not authorized' USING ERRCODE = '42501';
  END IF;

  IF p_password IS NULL OR length(p_password) < 6 THEN
    RAISE EXCEPTION 'admin_set_password: password must be at least 6 characters';
  END IF;

  UPDATE auth.users
  SET encrypted_password = crypt(p_password, gen_salt('bf')),
      updated_at = NOW()
  WHERE id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'admin_set_password: no user with id %', p_user_id;
  END IF;
END;
$$;

-- -------------------------------------------------------- 4.3 approve user
DROP FUNCTION IF EXISTS public.admin_set_approved(UUID, BOOLEAN);
CREATE OR REPLACE FUNCTION public.admin_set_approved(p_user_id UUID, p_approved BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'admin_set_approved: not authorized' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.profiles (id, email, approved, approved_at, approved_by)
  SELECT u.id, LOWER(u.email), p_approved,
         CASE WHEN p_approved THEN NOW() END,
         CASE WHEN p_approved THEN auth.uid() END
  FROM auth.users u WHERE u.id = p_user_id
  ON CONFLICT (id) DO UPDATE
    SET approved = EXCLUDED.approved,
        approved_at = EXCLUDED.approved_at,
        approved_by = EXCLUDED.approved_by;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'admin_set_approved: no user with id %', p_user_id;
  END IF;
END;
$$;

-- ------------------------------------------------- 4.4 grant/revoke admin
DROP FUNCTION IF EXISTS public.admin_set_admin(UUID, BOOLEAN);
CREATE OR REPLACE FUNCTION public.admin_set_admin(p_user_id UUID, p_is_admin BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'admin_set_admin: not authorized' USING ERRCODE = '42501';
  END IF;

  -- Guard against the obvious footgun: an admin revoking their own rights would
  -- leave no way back in except the SQL editor.
  IF p_user_id = auth.uid() AND NOT p_is_admin THEN
    RAISE EXCEPTION 'admin_set_admin: you cannot revoke your own admin rights';
  END IF;

  UPDATE public.profiles SET is_admin = p_is_admin WHERE id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'admin_set_admin: no profile for user %', p_user_id;
  END IF;
END;
$$;

-- --------------------------------------------------------- 4.5 delete user
-- Removes the account and everything it owned. The foreign keys cascade, but the
-- deletes are explicit so the intent (and the order) is obvious.
DROP FUNCTION IF EXISTS public.admin_delete_user(UUID);
CREATE OR REPLACE FUNCTION public.admin_delete_user(p_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'admin_delete_user: not authorized' USING ERRCODE = '42501';
  END IF;

  IF p_user_id = auth.uid() THEN
    RAISE EXCEPTION 'admin_delete_user: you cannot delete your own account';
  END IF;

  DELETE FROM public.todo_shares WHERE owner_id = p_user_id OR shared_with_id = p_user_id;
  DELETE FROM public.notes WHERE user_id = p_user_id;
  DELETE FROM public.todos WHERE user_id = p_user_id;
  DELETE FROM public.profiles WHERE id = p_user_id;

  DELETE FROM auth.users WHERE id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'admin_delete_user: no user with id %', p_user_id;
  END IF;
END;
$$;


-- ==============================================================================
-- 5. ROW LEVEL SECURITY
-- ==============================================================================

ALTER TABLE public.todos       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.todo_shares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles    ENABLE ROW LEVEL SECURITY;


-- --------------------------------------------------------------- 5.1 todos
DROP POLICY IF EXISTS "Users can view own or shared todos" ON public.todos;
DROP POLICY IF EXISTS "Users can insert own todos" ON public.todos;
DROP POLICY IF EXISTS "Users can update own or shared todos" ON public.todos;
DROP POLICY IF EXISTS "Users can delete own or shared todos" ON public.todos;

-- SELECT: l'utente può vedere i propri task OPPURE quelli di un gruppo condiviso
-- con lui. Il confronto sul gruppo è quello che rende la condivisione "per gruppo":
--   s.group_name IS NULL            -> tutta la lista
--   s.group_name = <gruppo del todo> -> solo quel sottogruppo
-- `is_approved` is the gate: a pending account matches nothing at all.
CREATE POLICY "Users can view own or shared todos"
ON public.todos FOR SELECT
TO authenticated
USING (
  public.is_approved(auth.uid())
  AND (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.todo_shares s
      WHERE s.owner_id = todos.user_id
        AND (
          s.shared_with_id = auth.uid()
          OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
        )
        AND (s.group_name IS NULL OR s.group_name = COALESCE(todos.group_name, 'Generale'))
    )
  )
);

-- INSERT: l'utente può inserire solo task con il proprio user_id
CREATE POLICY "Users can insert own todos"
ON public.todos FOR INSERT
TO authenticated
WITH CHECK (
  public.is_approved(auth.uid())
  AND auth.uid() = user_id
);

-- UPDATE: l'utente può modificare i propri task OPPURE quelli di un gruppo
-- condiviso con permesso 'edit'
CREATE POLICY "Users can update own or shared todos"
ON public.todos FOR UPDATE
TO authenticated
USING (
  public.is_approved(auth.uid())
  AND (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.todo_shares s
      WHERE s.owner_id = todos.user_id
        AND (
          s.shared_with_id = auth.uid()
          OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
        )
        AND (s.group_name IS NULL OR s.group_name = COALESCE(todos.group_name, 'Generale'))
        AND s.permission = 'edit'
    )
  )
);

-- DELETE: l'utente può eliminare i propri task OPPURE quelli di un gruppo
-- condiviso con permesso 'edit'
CREATE POLICY "Users can delete own or shared todos"
ON public.todos FOR DELETE
TO authenticated
USING (
  public.is_approved(auth.uid())
  AND (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.todo_shares s
      WHERE s.owner_id = todos.user_id
        AND (
          s.shared_with_id = auth.uid()
          OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
        )
        AND (s.group_name IS NULL OR s.group_name = COALESCE(todos.group_name, 'Generale'))
        AND s.permission = 'edit'
    )
  )
);


-- --------------------------------------------------------------- 5.2 notes
-- Deliberately the mirror image of the todos policies above, resolving against
-- the SAME public.todo_shares rows: a grant on a group covers its notes too,
-- which is what "shared with the actual group sharing method" means here.
DROP POLICY IF EXISTS "Users can view own or shared notes" ON public.notes;
DROP POLICY IF EXISTS "Users can insert own notes" ON public.notes;
DROP POLICY IF EXISTS "Users can update own or shared notes" ON public.notes;
DROP POLICY IF EXISTS "Users can delete own or shared notes" ON public.notes;

CREATE POLICY "Users can view own or shared notes"
ON public.notes FOR SELECT
TO authenticated
USING (
  public.is_approved(auth.uid())
  AND (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.todo_shares s
      WHERE s.owner_id = notes.user_id
        AND (
          s.shared_with_id = auth.uid()
          OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
        )
        AND (s.group_name IS NULL OR s.group_name = COALESCE(notes.group_name, 'Generale'))
    )
  )
);

CREATE POLICY "Users can insert own notes"
ON public.notes FOR INSERT
TO authenticated
WITH CHECK (
  public.is_approved(auth.uid())
  AND auth.uid() = user_id
);

CREATE POLICY "Users can update own or shared notes"
ON public.notes FOR UPDATE
TO authenticated
USING (
  public.is_approved(auth.uid())
  AND (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.todo_shares s
      WHERE s.owner_id = notes.user_id
        AND (
          s.shared_with_id = auth.uid()
          OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
        )
        AND (s.group_name IS NULL OR s.group_name = COALESCE(notes.group_name, 'Generale'))
        AND s.permission = 'edit'
    )
  )
);

CREATE POLICY "Users can delete own or shared notes"
ON public.notes FOR DELETE
TO authenticated
USING (
  public.is_approved(auth.uid())
  AND (
    auth.uid() = user_id
    OR EXISTS (
      SELECT 1 FROM public.todo_shares s
      WHERE s.owner_id = notes.user_id
        AND (
          s.shared_with_id = auth.uid()
          OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
        )
        AND (s.group_name IS NULL OR s.group_name = COALESCE(notes.group_name, 'Generale'))
        AND s.permission = 'edit'
    )
  )
);


-- --------------------------------------------------------- 5.3 todo_shares
DROP POLICY IF EXISTS "Owners can manage their shares" ON public.todo_shares;
DROP POLICY IF EXISTS "Recipients can view received shares" ON public.todo_shares;

-- Il proprietario può gestire (visualizzare, inserire, revocare) le proprie condivisioni
CREATE POLICY "Owners can manage their shares"
ON public.todo_shares FOR ALL
TO authenticated
USING (public.is_approved(auth.uid()) AND auth.uid() = owner_id)
WITH CHECK (public.is_approved(auth.uid()) AND auth.uid() = owner_id);

-- I destinatari possono visualizzare le condivisioni inviate a loro
CREATE POLICY "Recipients can view received shares"
ON public.todo_shares FOR SELECT
TO authenticated
USING (
  public.is_approved(auth.uid())
  AND (
    shared_with_id = auth.uid()
    OR LOWER(shared_with_email) = LOWER(auth.jwt() ->> 'email')
  )
);


-- ----------------------------------------------------------- 5.4 profiles
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;

-- A user reads their own row and nothing else. Read-only on purpose: there is NO
-- insert/update/delete policy here, so `approved`/`is_admin` cannot be set from the
-- client with the publishable key. Only the section 4 functions can change them.
CREATE POLICY "Users can view own profile"
ON public.profiles FOR SELECT
TO authenticated
USING (auth.uid() = id);

CREATE POLICY "Admins can view all profiles"
ON public.profiles FOR SELECT
TO authenticated
USING (public.is_admin(auth.uid()));


-- ==============================================================================
-- 6. PRIVILEGI TABELLARI (GRANT)
-- Nota: una tabella creata tramite script / SQL Editor può non ricevere i GRANT
-- automatici che la Dashboard assegna alle tabelle create dall'interfaccia.
-- Senza questi GRANT il client autenticato riceve:
--   permission denied for table todo_shares   (SQLSTATE 42501)
-- anche quando la query riguarda soltanto 'todos': le policy RLS sopra eseguono
-- una sottoquery su public.todo_shares, valutata con i privilegi del chiamante.
-- I GRANT decidono se la tabella è accessibile; le policy RLS decidono QUALI righe
-- sono visibili. Servono entrambi.
-- ==============================================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.todos       TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notes       TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.todo_shares TO anon, authenticated;
-- profiles: read-only, and RLS restricts it to your own row (or everything, for admins).
GRANT SELECT ON public.profiles TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- Functions default to EXECUTE for PUBLIC; take it back and hand it out narrowly.
REVOKE ALL ON FUNCTION public.is_admin(UUID) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.is_approved(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_admin(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_approved(UUID) TO authenticated;

REVOKE ALL ON FUNCTION public.admin_list_users() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_set_password(UUID, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_set_approved(UUID, BOOLEAN) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_set_admin(UUID, BOOLEAN) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_delete_user(UUID) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.admin_list_users() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_password(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_approved(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_admin(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_user(UUID) TO authenticated;


-- ==============================================================================
-- 7. YOUR ADMIN ACCOUNT
-- There is no API that can grant admin rights on purpose. Run this once, by hand,
-- with your own address, then reload the app:
--
--   UPDATE public.profiles
--   SET is_admin = TRUE, approved = TRUE
--   WHERE LOWER(email) = LOWER('you@example.com');
--
-- Verify with:
--   SELECT id, email, approved, is_admin FROM public.profiles ORDER BY created_at;
-- ==============================================================================
