-- ==============================================================================
-- ShareToDo - Complete Database Schema with Authentication & RLS & Sharing
-- Execute this script in your Supabase Dashboard -> SQL Editor
--
-- La condivisione può essere di DUE livelli:
--   group_name IS NULL        -> si condivide l'intera lista
--   group_name valorizzato    -> si condivide solo quel sottogruppo
-- ==============================================================================

-- 1. Tabella 'todos'
CREATE TABLE IF NOT EXISTS public.todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  group_name TEXT DEFAULT 'Generale',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid()
);

-- Assicurati che le colonne esistano se la tabella era già creata
ALTER TABLE public.todos ADD COLUMN IF NOT EXISTS group_name TEXT DEFAULT 'Generale';
ALTER TABLE public.todos ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid();

-- Indici di performance
CREATE INDEX IF NOT EXISTS idx_todos_user_id ON public.todos(user_id);
CREATE INDEX IF NOT EXISTS idx_todos_group_name ON public.todos(group_name);


-- 2. Tabella 'todo_shares' (Condivisione di gruppi/attività con altri utenti)
CREATE TABLE IF NOT EXISTS public.todo_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL DEFAULT auth.uid(),
  shared_with_email TEXT NOT NULL,
  shared_with_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  group_name TEXT,
  permission TEXT CHECK (permission IN ('read', 'edit')) DEFAULT 'edit',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migrazione per database già esistenti
ALTER TABLE public.todo_shares ADD COLUMN IF NOT EXISTS group_name TEXT;

-- L'unicità ora comprende il gruppo: la stessa persona può ricevere più gruppi.
-- COALESCE perché in un indice UNIQUE i NULL sono tutti distinti fra loro, quindi
-- senza di esso si potrebbero creare più condivisioni "intera lista" per la stessa email.
ALTER TABLE public.todo_shares DROP CONSTRAINT IF EXISTS todo_shares_owner_id_shared_with_email_key;
DROP INDEX IF EXISTS public.idx_todo_shares_unique;
CREATE UNIQUE INDEX IF NOT EXISTS idx_todo_shares_unique
  ON public.todo_shares (owner_id, LOWER(shared_with_email), COALESCE(group_name, '__all__'));

CREATE INDEX IF NOT EXISTS idx_todo_shares_owner ON public.todo_shares(owner_id);
CREATE INDEX IF NOT EXISTS idx_todo_shares_email ON public.todo_shares(LOWER(shared_with_email));
CREATE INDEX IF NOT EXISTS idx_todo_shares_recipient ON public.todo_shares(shared_with_id);


-- 3. Trigger automatico: quando un nuovo utente si registra, collega le condivisioni inviate alla sua email
CREATE OR REPLACE FUNCTION public.handle_new_user_shares()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.todo_shares
  SET shared_with_id = NEW.id
  WHERE LOWER(shared_with_email) = LOWER(NEW.email);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created_shares ON auth.users;
CREATE TRIGGER on_auth_user_created_shares
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_shares();


-- 4. ATTIVAZIONE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.todo_shares ENABLE ROW LEVEL SECURITY;


-- 5. POLICIES PER 'todos'
-- Elimina policy preesistenti per evitare conflitti
DROP POLICY IF EXISTS "Users can view own or shared todos" ON public.todos;
DROP POLICY IF EXISTS "Users can insert own todos" ON public.todos;
DROP POLICY IF EXISTS "Users can update own or shared todos" ON public.todos;
DROP POLICY IF EXISTS "Users can delete own or shared todos" ON public.todos;

-- SELECT: L'utente può vedere i propri task OPPURE quelli di un gruppo condiviso con lui.
-- Il confronto sul gruppo è quello che rende la condivisione "per gruppo":
--   s.group_name IS NULL            -> tutta la lista
--   s.group_name = <gruppo del todo> -> solo quel sottogruppo
CREATE POLICY "Users can view own or shared todos"
ON public.todos FOR SELECT
TO authenticated
USING (
  auth.uid() = user_id
  OR EXISTS (
    SELECT 1 FROM public.todo_shares s
    WHERE s.owner_id = todos.user_id
      AND (
        s.shared_with_id = auth.uid()
        OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
      )
      AND (s.group_name IS NULL OR s.group_name = COALESCE(todos.group_name, 'Generale'))
  )
);

-- INSERT: L'utente può inserire solo task con il proprio user_id
CREATE POLICY "Users can insert own todos"
ON public.todos FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = user_id
);

-- UPDATE: L'utente può modificare i propri task OPPURE quelli di un gruppo condiviso con permesso 'edit'
CREATE POLICY "Users can update own or shared todos"
ON public.todos FOR UPDATE
TO authenticated
USING (
  auth.uid() = user_id
  OR EXISTS (
    SELECT 1 FROM public.todo_shares s
    WHERE s.owner_id = todos.user_id
      AND (
        s.shared_with_id = auth.uid()
        OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
      )
      AND (s.group_name IS NULL OR s.group_name = COALESCE(todos.group_name, 'Generale'))
      AND s.permission = 'edit'
  )
);

-- DELETE: L'utente può eliminare i propri task OPPURE quelli di un gruppo condiviso con permesso 'edit'
CREATE POLICY "Users can delete own or shared todos"
ON public.todos FOR DELETE
TO authenticated
USING (
  auth.uid() = user_id
  OR EXISTS (
    SELECT 1 FROM public.todo_shares s
    WHERE s.owner_id = todos.user_id
      AND (
        s.shared_with_id = auth.uid()
        OR LOWER(s.shared_with_email) = LOWER(auth.jwt() ->> 'email')
      )
      AND (s.group_name IS NULL OR s.group_name = COALESCE(todos.group_name, 'Generale'))
      AND s.permission = 'edit'
  )
);


-- 6. POLICIES PER 'todo_shares'
DROP POLICY IF EXISTS "Owners can manage their shares" ON public.todo_shares;
DROP POLICY IF EXISTS "Recipients can view received shares" ON public.todo_shares;

-- Il proprietario può gestire (visualizzare, inserire, revocare) le proprie condivisioni
CREATE POLICY "Owners can manage their shares"
ON public.todo_shares FOR ALL
TO authenticated
USING (auth.uid() = owner_id)
WITH CHECK (auth.uid() = owner_id);

-- I destinatari possono visualizzare le condivisioni inviate a loro
CREATE POLICY "Recipients can view received shares"
ON public.todo_shares FOR SELECT
TO authenticated
USING (
  shared_with_id = auth.uid()
  OR LOWER(shared_with_email) = LOWER(auth.jwt() ->> 'email')
);


-- ==============================================================================
-- 7. PRIVILEGI TABELLARI (GRANT)
-- Nota: una tabella creata tramite script / SQL Editor può non ricevere i GRANT
-- automatici che la Dashboard assegna alle tabelle create dall'interfaccia.
-- Senza questi GRANT il client autenticato riceve:
--   permission denied for table todo_shares   (SQLSTATE 42501)
-- anche quando la query riguarda soltanto 'todos': le policy RLS sopra eseguono
-- una sottoquery su public.todo_shares, valutata con i privilegi del chiamante.
-- I GRANT decidono se la tabella è accessibile; le policy RLS decidono QUALI righe
-- sono visibili. Servono entrambi.
-- ==============================================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.todos       TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.todo_shares TO anon, authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
